[versions]
# Plugins
agp = "8.13.2"
kotlin = "2.3.0"

# Dependencies
appcompat = "1.7.1"
material = "1.12.0"
multidex = "2.0.1"
junit = "4.13.2"
junitJupiter = "6.0.1"
junitPlatform = "6.0.1"
kluent = "1.73"
mockk = "1.14.7"
mockkAgentJvm = "1.14.7"
apacheCommonsIo = "2.21.0"
apacheCommonsLang3 = "3.20.0"

[libraries]
# AndroidX
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }

# Google
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitJupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junitJupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform" }
kluent = { group = "org.amshove.kluent", name = "kluent", version.ref = "kluent" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-agent-jvm = { group = "io.mockk", name = "mockk-agent-jvm", version.ref = "mockkAgentJvm" }

# Utils
apache-commons-io = { group = "commons-io", name = "commons-io", version.ref = "apacheCommonsIo" }
apache-commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommonsLang3" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
