[versions]
# Plugins
agp = "9.0.0"
kotlin = "2.3.0"
ksp = "2.3.5"
hilt = "2.59"


# Dependencies
appcompat = "1.7.1"
material = "1.13.0"
multidex = "2.0.1"
coreSplashscreen = "1.0.1"
junit = "4.13.2"
junitJupiter = "6.0.2"
junitPlatform = "6.0.2"
kluent = "1.73"
mockk = "1.14.9"
mockkAgentJvm = "1.14.9"
apacheCommonsIo = "2.21.0"
apacheCommonsLang3 = "3.20.0"
kotlinxCoroutines = "1.10.2"
androidxLifecycle = "2.8.7"

[libraries]
# AndroidX
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }

# Google
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Kotlin
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitJupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junitJupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform" }
kluent = { group = "org.amshove.kluent", name = "kluent", version.ref = "kluent" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-agent-jvm = { group = "io.mockk", name = "mockk-agent-jvm", version.ref = "mockkAgentJvm" }

# Utils
apache-commons-io = { group = "commons-io", name = "commons-io", version.ref = "apacheCommonsIo" }
apache-commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommonsLang3" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
