# This workflow will check the fastlane folder for syntax errors

name: Fastlane Syntax Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-fastlane-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v1
