# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Assemble Release

on:
  push:
    branches: [ master, development, feature/* ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: |
          echo "$(pwd)"
          cd sudoq-app
          chmod +x gradlew
    - name: assemble release with Gradle //build would try to build playground as well
      run: |
          echo "$(pwd)"      
          cd sudoq-app
          ./gradlew assembleRelease
