# This workflow runs the kotlin unit tests in sudoqmodel

name: Model Junit Tests for Kotlin

on:
  push:
    branches: [ master, development, feature/* ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: |
          echo "$(pwd)"
          cd sudoq-app
          chmod +x gradlew
    - name: junit tests in model with Gradle
      run: |
          echo "$(pwd)"
          cd sudoq-app
          ./gradlew sudoqapp:testDebugUnitTest
    - name: Upload app unit test report
      if: failure()
      uses: actions/upload-artifact@v6
      with:
        name: sudoqapp-unit-test-report
        path: sudoq-app/sudoqapp/build/reports/tests/testDebugUnitTest/
